sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
      - CS_CHECK=true

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source --no-scripts

script:
  - composer test
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: AKIAJDDM5YXDN774B3VA
    secret_access_key:
      secure: $AWS_SECRET_KEY
    application: zf3-web
    deployment_group: zf-devteam
    region: us-east-1
    on:
      branch: master

notifications:
  email: true
