sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
      - CS_CHECK=true

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source --no-scripts

script:
  - composer test
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

after_success:
  - .deploy/travis_deploy.sh $DEPLOY_TOKEN $SITE_NAME $TRAVIS_COMMIT

notifications:
  email: true
