sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
      - CS_CHECK=true

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source --no-scripts

script:
  - composer test
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

after_success:
  - curl --header "Content-Type: application/x-zfweb-deploy+json" --header "Authorization: Bearer ${DEPLOY_TOKEN}" --request POST --data '{"site":"'"${SITE_NAME}"'","commit":"'"${TRAVIS_COMMIT}"'"}' https://zf-node1.zend.com

notifications:
  email: true
